use_frameworks!

platform :ios, '10.0'

target 'dragSort_Example' do
  pod 'dragSort', :path => '../'

  #
  pod 'SnapKit'
  #
  pod 'Reusable'

  target 'dragSort_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 9.4.0'
  end
end
